routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('clientes.index');
});

Route::get('/home', function(){
	return redirect()->route('clientes.index');
})->name('home');

Route::post('/contacto','ContactoController@contacto')->name('contacto');

Route::resource('/tickets','TicketsController')->middleware('auth');

Route::resource('/remisiones','RemisionesController')->middleware('auth');
Route::resource('/compras','ComprasController')->middleware('auth');

Route::resource('/clientes','ClientesController')->middleware('auth');
Route::resource('/proveedores','ProveedoresController')->middleware('auth');

Route::resource('/laboratorios','LaboratoriosController')->middleware('auth');
Route::resource('/medicamentos','MedicamentosController')->middleware('auth');
Route::resource('/rutas','RutasController')->middleware('auth');

Route::post('/reporteClientes','ReportesController@reporteClientes')->name('reporteClientes')->middleware('auth');
Route::post('/reporteProveedores','ReportesController@reporteProveedores')->name('reporteProveedores')->middleware('auth');


Route::get('/ticketsAs','TicketsController@ticketsAs')->name('ticketsAs');
Route::get('/provsAs','TicketsController@provsAs')->name('provsAs');
Route::get('/rutasAs','RutasController@rutasAs')->name('rutasAs');
Route::get('/ticketAs','TicketsController@ticketAs')->name('ticketAs');
Route::get('/ticketPAs','TicketsController@ticketPAs')->name('ticketPAs');
Route::get('/laboratorioAs','LaboratoriosController@laboratorioAs')->name('laboratorioAs');
Route::get('/descripcionAs','RemisionesController@descripcionAs')->name('descripcionAs');

Route::get('/cambiar', 'UsuariosController@cambiar')->name('cambiar')->middleware('auth');
Route::post('/cambio', 'UsuariosController@cambio')->name('cambio')->middleware('auth');
Route::resource('/usuarios','UsuariosController')->middleware('auth');

Route::resource('/pagos','PagosController')->middleware('auth');
Route::resource('/abonos','AbonosController')->middleware('auth');

Route::get('/catalogos', 'MedicamentosController@catalogos')->name('catalogos')->middleware('auth');

app/Http/Controllers/ComprasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use NumerosEnLetras;

class ComprasController extends Controller
{
    public function create()
    {
      return view('compras.crearcompra');
    }

    public function index(Request $request){
      app('App\Http\Controllers\ProveedoresController')->comprueba();
      $busqueda = $request->get('busquedaId');
      $compras=DB::table('compras')
      ->selectRaw('compras.*,proveedores.*, compras.id as idre')
      ->where('proveedores.nombre','LIKE', "%$busqueda%")
      ->where('compras.estado',1)
      ->join('proveedores','compras.id_proveedor','=','proveedores.id')
      ->orderBy('compras.id','desc')
      ->paginate(10);
      $abonos=DB::table('abonos')
      ->where('estado',1)
      ->orderBy('fecha','desc')
      ->get();
      return view('compras.index',compact('compras','abonos'));
    }

    public function store(Request $request)
    {
      if($request->importeTotal==null){
        $request->importeTotal=0;
      }

      $id = DB::table('compras')->insertGetId(
          [
           'id_proveedor' => $request->id,
           'importe' => $request->importeTotal,
           'fecha' => $request->fecha,
           'estado' => 1,
           'fechafin' => $request->fechafin,
          ]
      );

      for($i = 1; $i < 25; $i++){
        DB::table('articulos')->insert(
            [
             'cantidad' => $request["cantidad$i"],
             'descripcion' => $request["descripcion$i"],
             'precio' => $request["precio$i"],
             'iva' => $request["iva$i"],
             'importe' => $request["importe$i"],
             'id_compra' => $id,
            ]
        );
      }
      app('App\Http\Controllers\ProveedoresController')->comprueba();
      return redirect()->route('compras.index')->with('info','Se guardó correctamente');
    }

    public function update(Request $request, $id)
    {
      app('App\Http\Controllers\ProveedoresController')->comprueba();
      if($request->importeTotal==null){
        $request->importeTotal=0;
      }
      DB::table('compras')
      ->where('id',$id)->update(
          [
           'id_proveedor' => $request->id,
           'importe' => $request->importeTotal,
           'estado' => 1,
           'fecha' => $request->fecha,
           'fechafin' => $request->fechafin,
          ]
      );

      for($i = 1; $i < 25; $i++){
        DB::table('articulos')
        ->where('id',$request["id$i"])->update(
            [
             'cantidad' => $request["cantidad$i"],
             'descripcion' => $request["descripcion$i"],
             'precio' => $request["precio$i"],
             'iva' => $request["iva$i"],
             'importe' => $request["importe$i"],
             'id_compra' => $id,
            ]
        );
      }
      app('App\Http\Controllers\ProveedoresController')->comprueba();
      return redirect()->route('compras.index')->with('info','Se actualizó correctamente');
    }

    public function descripcionAs(Request $request)
    {
      $pal=strtoupper($request->term);

       $descripcion=DB::table('catalogo')
       ->selectRaw('catalogo.nombre')
       ->where('catalogo.estado',1)
       ->where(function ($query) use ($pal) {
           $query->where('catalogo.nombre','LIKE', "%$pal%")
           ->orWhere('catalogo.descripcion','LIKE', "%$pal%")
           ->orWhere('catalogo.codigo','LIKE', "%$pal%")
           ->orWhere('catalogo.sustancia','LIKE', "%$pal%")
           ->orWhere('catalogo.indice','LIKE', "%$pal%")
           ->orWhere('catalogo.oferta','LIKE', "%$pal%")
           ->orWhere('laboratorios.laboratorio','LIKE', "%$pal%");
       })
       ->join('laboratorios','catalogo.id_laboratorio','=','laboratorios.id')
       ->limit(10)
       ->get();


      foreach ($descripcion as $c) {
         $rDescripcion[]=[
           'nombre'=>$c->nombre,
           'label'=>$c->nombre
         ];

      }
      return Response($rDescripcion);
    }

    public function destroy($id){
      DB::table('compras')
      ->where('id',$id)->update(
          [
           'estado' => 2
          ]
      );
      return redirect()->route('compras.index')->with('info','Se eliminó correctamente');
    }

    public function edit($id){
      $articulos=DB::table('articulos')
      ->where('id_compra',$id)
      ->get();

      $compra=DB::table('compras')
      ->selectRaw('*,compras.id as idre')
      ->join('proveedores','compras.id_proveedor','=','proveedores.id')
      ->where('compras.id',$id)
      ->first();
      return view('compras.edit',compact('compra','articulos'));
    }

    public function show($id){
      $articulos=DB::table('articulos')
      ->where('id_compra',$id)
      ->get();

      $compra=DB::table('compras')
      ->selectRaw('*,compras.id as idre')
      ->join('proveedores','compras.id_proveedor','=','proveedores.id')
      ->where('compras.id',$id)
      ->first();
      $letras= strtoupper(NumerosEnLetras::convertir($compra->importe,'M.N.',true));
      return view('compras.show',compact('compra','articulos','letras'));
    }
}

resources/views/compras/crearcompra.blade.php
@extends('layouts.main')

@section('seccion')
  Compras / Crear
@endsection

@section('titulo')
  Nueva Compra
@endsection

@section('descripcion')
  Agregar datos de compra.
@endsection



@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection

@section('contenido')

<div class="container text-center">
  <form action="{{route('compras.store')}}" method="POST">
    <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
      <div class="row">

            <div class="col-12">
              <div class="text-center border border-light p-5" >
                  Proveedor
                  <div class="input-group mb-2 mr-sm-2">
                    <input type="text" id="nombre" required name="nombre" style="text-transform: uppercase" class="form-control" placeholder="NOMBRE">
                    <input type="hidden" id="nombreAlt" name="nombreAlt" class="form-control" placeholder="Nombre">
                    <div class="input-group-prepend">
                     <a class="input-group-text btn  btn-danger" onclick="limpiarCampo()">
                      <i class="fa fa-trash-o"></i>
                     </a>
                    </div>
                  </div>
                  <input type="text" id="id" name="id" hidden class="form-control mb-2" >
                  <input type="text" id="direccion" name="direccion" readonly class="form-control mb-2" placeholder="DIRECCIÓN">
                  <input type="text" id="telefono" name="telefono" readonly class="form-control mb-2" placeholder="TELÉFONO">
                  <p>Fecha inicial</p>
                  <input type="date" id="fecha" required name="fecha" class="form-control mb-2" placeholder="FECHA">
                  <p>Fecha final</p>
                  <input type="date" id="fechafin" required name="fechafin" class="form-control mb-2" placeholder="FECHA">

              </div>
            </div>
      </div>
      <div class="row">

            <div class="col-12">
              <div class="text-center border border-light p-5" >
                <div class="row">
                  <div class="col">
                    Cantidad
                  </div>
                  <div class="col">
                    Descripción
                  </div>
                  <div class="col">
                    Precio Unitario
                  </div>
                  <div class="col">
                    IVA (%)
                  </div>
                  <div class="col">
                    Importe
                  </div>
                  <br><br>
                </div>
                @for($i = 1; $i < 25; $i++)
                <div class="row">
                  <div class="col">
                    <input type="number" step="0.01"name="cantidad{{$i}}" id="cantidad{{$i}}" onkeyup="calcular({{$i}})" class="form-control" placeholder="Cantidad">
                  </div>
                  <div class="col">
                    <textarea name="descripcion{{$i}}" id="descripcion{{$i}}" class="form-control" placeholder="Descripción"></textarea>
                  </div>
                  <div class="col">
                    <input type="number" step="0.01"name="precio{{$i}}" id="precio{{$i}}" onkeyup="calcular({{$i}})" class="form-control" placeholder="Precio Unitario">
                  </div>
                  <div class="col">
                    <input type="number" step="0.01"name="iva{{$i}}" id="iva{{$i}}" class="form-control" placeholder="IVA">
                  </div>
                  <div class="col">
                    <input type="number" step="0.01"name="importe{{$i}}"  id="importe{{$i}}" class="form-control importes" placeholder="Importe">
                  </div>
                  <br><br><br><br>
                </div>
                @include('compras.script')
                @endfor
              </div>
            </div>
      </div>
      <div class="row">

            <div class="col-12">
              <div class="text-center border border-light p-5" >
                <div class="row">
                  <div class="col-sm">
                    <input type="number" class="form-control" placeholder="Cantidad" hidden>
                  </div>
                  <div class="col-sm">
                    <input type="number" class="form-control" placeholder="Cantidad" hidden>
                  </div>
                  <div class="col-sm">
                    <input type="number" class="form-control" placeholder="Cantidad" hidden>
                  </div>
                  <div class="col-sm">
                    <h3>Importe total:</h3>
                  </div>
                  <div class="col-sm">
                    <input type="number" step="0.01"id="importeTotal" name="importeTotal" class="form-control" placeholder="Importe Total" >
                  </div>
                  <br><br>
                </div>
              </div>
            </div>
      </div>
      <div class="d-flex">
        <div class="mr-auto p-2">
          <button type="submit" class="btn  btn-info text-white">Guardar</button>
          <a href="{{route('compras.index')}}" class="btn  btn-secondary">Cancelar</a>
        </div>
      </div>
      </form>
    </div>
  @include('compras.scripjs')
@endsection

resources/views/compras/edit.blade.php
@extends('layouts.main')

@section('seccion')
  Compras / Editar
@endsection

@section('titulo')
  Remisión Número: {{$compra->idre}}
@endsection

@section('descripcion')
  Editar datos de remisión
@endsection



@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection

@section('contenido')
    <div class="container text-center">
      <form action="{{route('compras.update',$compra->idre)}}" method="POST">
         <input type="hidden" name="_method" value="PUT">
         <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
            <div class="row">
                  <div class="col-12">
                    <div class="text-center border border-light p-5" >
                        Proveedor
                        <div class="input-group mb-2 mr-sm-2">
                          <input type="text" disabled value="{{$compra->nombre}}" id="nombre" required name="nombre" class="form-control" style="text-transform: uppercase" placeholder="NOMBRE">
                          <input type="hidden" value="{{$compra->nombre}}" id="nombreAlt" name="nombreAlt" class="form-control" placeholder="Nombre">
                          <div class="input-group-prepend">
                           <a class="input-group-text btn  btn-danger" onclick="limpiarCampo()">
                            <i class="fa fa-trash-o"></i>
                           </a>
                          </div>
                        </div>
                        <input type="text" value="{{$compra->id_proveedor}}" hidden id="id" name="id"  class="form-control mb-2" >
                        <input type="text" value="{{$compra->direccion}}" id="direccion" name="direccion" readonly class="form-control mb-2" placeholder="DIRECCIÓN">
                        <input type="text" value="{{$compra->telefono}}" id="telefono" name="telefono" readonly class="form-control mb-2" placeholder="TELÉFONO">
                        <p>Fecha inicial</p>
                        <input type="date" value="{{$compra->fecha}}" id="fecha" required name="fecha" class="form-control mb-2" placeholder="FECHA">
                        <p>Fecha final</p>
                        <input type="date" value="{{$compra->fechafin}}" id="fechafin" required name="fechafin" class="form-control mb-2" placeholder="FECHA">

                    </div>
                  </div>
            </div>
            <div class="row">
                  <div class="col-12">
                    <div class="text-center border border-light p-5" >
                      <div class="row">
                        <div class="col">
                          Cantidad
                        </div>
                        <div class="col">
                          Descripción
                        </div>
                        <div class="col">
                          Precio Unitario
                        </div>
                        <div class="col">
                          IVA (%)
                        </div>
                        <div class="col">
                          Importe
                        </div>
                        <br><br>
                      </div>
                      @for($i = 1; $i < 25; $i++)
                      <div class="row">
                        <div class="col">
                          <input type="hidden" name="id{{$i}}" value="{{$articulos[$i-1]->id}}">
                          <input type="number" step="0.01"value="{{$articulos[$i-1]->cantidad}}" name="cantidad{{$i}}" id="cantidad{{$i}}" onkeyup="calcular({{$i}})" class="form-control" placeholder="Cantidad">
                        </div>
                        <div class="col">
                          <textarea name="descripcion{{$i}}" id="descripcion{{$i}}" class="form-control" placeholder="Descripción">{{$articulos[$i-1]->descripcion}}</textarea>
                        </div>
                        <div class="col">
                          <input type="number" step="0.01"value="{{$articulos[$i-1]->precio}}" name="precio{{$i}}" id="precio{{$i}}" onkeyup="calcular({{$i}})" class="form-control" placeholder="Precio Unitario">
                        </div>
                        <div class="col">
                          <input type="number"step="0.01" value="{{$articulos[$i-1]->iva}}" name="iva{{$i}}" id="iva{{$i}}" class="form-control" placeholder="IVA">
                        </div>
                        <div class="col">
                          <input type="number"step="0.01" value="{{$articulos[$i-1]->importe}}" name="importe{{$i}}"  id="importe{{$i}}" class="form-control importes" placeholder="Importe">
                        </div>
                        <br><br><br><br>
                      </div>
                      @include('compras.script')
                      @endfor
                    </div>
                  </div>
            </div>
            <div class="row">
                  <div class="col-12">
                    <div class="text-center border border-light p-5" >
                      <div class="row">
                        <div class="col-sm">
                          <input type="number" class="form-control" placeholder="Cantidad" hidden>
                        </div>
                        <div class="col-sm">
                          <input type="number" class="form-control" placeholder="Cantidad" hidden>
                        </div>
                        <div class="col-sm">
                          <input type="number" class="form-control" placeholder="Cantidad" hidden>
                        </div>
                        <div class="col-sm">
                          <h3>Importe total:</h3>
                        </div>
                        <div class="col-sm">
                          <input type="number" step="0.01"value="{{$compra->importe}}" id="importeTotal" name="importeTotal" class="form-control" placeholder="Importe Total" >
                        </div>
                        <br><br>
                      </div>
                    </div>
                  </div>
            </div>
            <div class="d-flex">
              <div class="mr-auto p-2">
                <button type="submit" class="btn  btn-info text-white">Actualizar</button>
                <a href="{{route('compras.index')}}" class="btn  btn-secondary">Cancelar</a>
              </div>
              <div class="p-2"><button type="button" onclick="$('#formDes').submit();" class="btn  btn-danger">Eliminar</button></div>
            </div>
      </form>
    </div>
    {!! Form::model($compra,['route'=>['compras.destroy', $compra->idre], 'method'=>'DELETE', 'id'=>'formDes','onsubmit'=>'return confirm("¿Seguro que desea eliminarlo?")']) !!}
    {!!Form::close()!!}

  <script type="text/javascript">
    function cerrar() {
        $('#not').remove();
    }
  </script>
  @include('compras.scripjs')
@endsection

resources/views/compras/index.blade.php
@extends('layouts.main')

@section('seccion')
  Compras
@endsection

@section('titulo')
  Gestor de compras
@endsection

@section('boton')
  <a href="{{route('compras.create')}}" class="btn  btn-info text-white"><i class="fa fa-plus"></i> Registrar nueva compra</a>
@endsection

@section('descripcion')
  Panel de control para gestionar las compras
@endsection


@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection


@section('contenido')
{{Form::open(['route'=>'compras.index','method'=>'GET'])}}
  @include('layouts.busqueda')
{{Form::close()}}
  <table class="table table-hover table-outline text-center">
    <thead class="thead-light">
          <tr>
            <th scope="col">Número de remisión</th>
            <th scope="col">Proveedor</th>
            <th scope="col">Fecha Inicio</th>
            <th scope="col">Fecha Vencimiento</th>
            <th scope="col">Importe</th>
            <th scope="col">Pagado</th>
            <th scope="col">Pendiente</th>
            <th scope="col">Días</th>
            <!--<th scope="col">Ver</th>-->
            <th scope="col">Editar</th>
            <th scope="col">Añadir abono</th>
          </tr>
        </thead>
        <tbody>
          @foreach($compras as $r)

              @php
              $fecha1 = new DateTime("NOW");
              $fecha1 = new \DateTime($fecha1->format("Y-m-d"));

              $fecha2 = new DateTime($r->fechafin);
              $diff = $fecha1->diff($fecha2);
              $cont=0;
              $palabra="";
              @endphp

              @if($r->abono==1)
                @php $palabra="Completado."; @endphp
                <tr class="table-success">
              @elseif($r->abono==2)
                @php $palabra="Completado a destiempo."; @endphp
                <tr class="table-warning">
              @elseif($r->abono==3)
                @if($diff->days!=0)
                  @php $palabra="Quedan: ".$diff->days." días."; @endphp
                @else
                  @php $palabra="Vence hoy"; @endphp
                @endif
                <tr>
              @elseif($r->abono==4)
                @php $palabra="Venció hace: ".$diff->days." días."; @endphp
                <tr class="table-danger">
              @endif
              <th scope="row">{{$r->idre}}</th>
              <td>{{$r->nombre}}</td>
              <td>{{$r->fecha}}</td>
              <td>{{$r->fechafin}}</td>
              <td>${{number_format($r->importe,2)}}</td>
              @foreach($abonos as $p)
                @if($p->id_compra==$r->idre)
                  @php
                    $cont=$cont+$p->cantidad;
                  @endphp
                @endif
              @endforeach
              <td>${{number_format($cont,2)}}</td>
              <td>${{number_format($r->importe-$cont,2)}}</td>
              <td>
                {{$palabra}}
              </td>
              <!--<td>
                <a class="btn  btn-info text-white" target="_blank" href="{{route('compras.show',$r->idre)}}"><i class="fa fa-file-pdf-o "></i></a>
              </td>-->
              <td>
                <a class="btn  btn-info text-white" href="{{route('compras.edit',$r->idre)}}"><i class="icon-pencil "></i></a>
              </td>
              <td>
                <a class="btn  btn-info text-white" href="{{route('abonos.edit',$r->idre)}}"><i class="fa fa-usd "></i></a>
              </td>
            </tr>
          @endforeach

        </tbody>
      </table>
      {!!$compras->appends(Request::only(['nombre']))->render()!!}
      @endsection

resources/views/compras/scripjs.blade.php
<script>

const proveedor = {
     source: '/ticketPAs',
     minLength: 2,
     autoFocus: true,
     select:function (e,ui) {

        $("#nombreAlt").val(ui.item.nombre);
        $("#direccion").val(ui.item.direccion);
        $("#telefono").val(ui.item.telefono);
        $("#id").val(ui.item.id);
        $("#nombre").attr('disabled', true);
        $("#inicial").attr('required', true);
        $("#final").attr('required', true);
     }
};

$('#nombre').autocomplete(proveedor);


function limpiarCampo() {
  $("#nombreAlt").val("");
  $("#nombre").val("");
  $("#direccion").val("");
  $("#clave").val("");
  $("#telefono").val("");
  $("#nombre").attr('disabled', false);
}

  function calcularFinal() {
    console.log("aquí");
    var importeTotal = 0;
    for (var i = 1; i < 25; i++) {
      var temp;
      if($("#importe"+i).val()==""){
        temp=0;
        console.log("aqui vale " + temp);
      }else{
        temp=parseFloat($("#importe"+i).val());
        console.log("aqui vale " + temp);
      }
      importeTotal=parseFloat(importeTotal)+parseFloat(temp);
      console.log(importeTotal);
    }
    $("#importeTotal").val(parseFloat(importeTotal).toFixed(2));
  }
  $(document).on("wheel", "input[type=number]", function (e) {
    $(this).blur();
});

function calcular(id) {
  var itemp=parseFloat($("#precio"+id).val()).toFixed(2)*parseFloat($("#cantidad"+id).val()).toFixed(2);

  $("#importe"+id).val(itemp.toFixed(2));
  calcularFinal();
}

$(document).on("keypress", 'form', function (e) {
    var code = e.keyCode || e.which;
    if (code == 13) {
        e.preventDefault();
        return false;
    }
});
</script>

resources/views/compras/script.blade.php
<script>
  const descripcion{{$i}} = {
       source: '/descripcionAs',
       minLength: 2,
       autoFocus: true,
       select:function (e,ui) {
          $("#descripcion{{$i}}").val(ui.item.descripcion);
       }
  };

  $('#descripcion{{$i}}').autocomplete(descripcion{{$i}});
</script>

resources/views/compras/show.blade.php
<?php
include(app_path().'\..\public\Fpdf181\fpdf.php');
class PDF extends FPDF
{
	function Header(){
			$this->Image('../public/img/fondo.png',-1,-2,216.5);
      $this->SetFont('Arial','',14);
			$this->SetTextColor(227,28,36);
			$this->text(182,17.1,utf8_decode($this->r->idre));
			$this->SetTextColor(0,0,0);
			$this->SetFont('Arial','',10);
      $this->text(172.5,35,utf8_decode($this->fechao));
			$this->SetFont('Arial','',9);
      $this->text(37,51.5,utf8_decode($this->r->id));
      $this->text(31,58.5,utf8_decode($this->r->nombre));
      $this->text(172,52.5,utf8_decode(1));
      $this->text(159,62.5,utf8_decode("A-01"));
      $this->text(31,66,utf8_decode($this->r->direccion));
      $this->text(31,73.5,utf8_decode($this->r->telefono));
      $this->SetFont('Arial','',8);
      $salto=0;
      foreach ($this->c as $c) {
        if($c->cantidad!="" || $c->cantidad!=null){
          $this->text(13,90+$salto,utf8_decode($c->cantidad));
          $this->text(24,90+$salto,utf8_decode($c->descripcion));
          $this->text(147,90+$salto,utf8_decode("$".number_format($c->precio,2)));
          $this->text(166,90+$salto,utf8_decode($c->iva."%"));
          $this->text(185,90+$salto,utf8_decode("$".number_format($c->importe,2)));
        }
        $salto=$salto+5;
        $this->Ln(6);
      }
      $this->SetFont('Arial','',8);
      $this->text(136,237,utf8_decode("IMPORTE TOTAL"));
      $this->text(186,237,utf8_decode("$".number_format($this->r->importe,2)));
      $this->text(16,249.5,utf8_decode("$".$this->l));
      $this->text(35,260.3,utf8_decode(number_format($this->r->importe,2)));
      $this->text(47,267,utf8_decode("3"));
      //$this->setXY(10,30);
      //$this->multicell(80,7,utf8_decode("DIRECCIÓN: ".$this->r->direccion1),0,"L",false);


	}

}

$pdf = new PDF('P','mm',array(216,279));
$pdf->l=$letras;
$pdf->c=$articulos;
$pdf->r=$compra;
$pdf->fechao = date("d      m     Y", strtotime($pdf->r->fecha));
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->Output();
exit();


?>