routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('clientes.index');
});

Route::get('/home', function(){
	return redirect()->route('clientes.index');
})->name('home');

Route::post('/contacto','ContactoController@contacto')->name('contacto');

Route::resource('/tickets','TicketsController')->middleware('auth');

Route::resource('/remisiones','RemisionesController')->middleware('auth');
Route::resource('/compras','ComprasController')->middleware('auth');

Route::resource('/clientes','ClientesController')->middleware('auth');
Route::resource('/proveedores','ProveedoresController')->middleware('auth');

Route::resource('/laboratorios','LaboratoriosController')->middleware('auth');
Route::resource('/medicamentos','MedicamentosController')->middleware('auth');
Route::resource('/rutas','RutasController')->middleware('auth');

Route::post('/reporteClientes','ReportesController@reporteClientes')->name('reporteClientes')->middleware('auth');
Route::post('/reporteProveedores','ReportesController@reporteProveedores')->name('reporteProveedores')->middleware('auth');


Route::get('/ticketsAs','TicketsController@ticketsAs')->name('ticketsAs');
Route::get('/provsAs','TicketsController@provsAs')->name('provsAs');
Route::get('/rutasAs','RutasController@rutasAs')->name('rutasAs');
Route::get('/ticketAs','TicketsController@ticketAs')->name('ticketAs');
Route::get('/ticketPAs','TicketsController@ticketPAs')->name('ticketPAs');
Route::get('/laboratorioAs','LaboratoriosController@laboratorioAs')->name('laboratorioAs');
Route::get('/descripcionAs','RemisionesController@descripcionAs')->name('descripcionAs');

Route::get('/cambiar', 'UsuariosController@cambiar')->name('cambiar')->middleware('auth');
Route::post('/cambio', 'UsuariosController@cambio')->name('cambio')->middleware('auth');
Route::resource('/usuarios','UsuariosController')->middleware('auth');

Route::resource('/pagos','PagosController')->middleware('auth');
Route::resource('/abonos','AbonosController')->middleware('auth');

Route::get('/catalogos', 'MedicamentosController@catalogos')->name('catalogos')->middleware('auth');

app/Http/Controllers/AbonosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class AbonosController extends Controller
{

    public function edit($id)
    {
      $abonos=DB::table('abonos')
      ->where('id_compra',$id)
      ->where('estado',1)
      ->orderBy('fecha','desc')
      ->get();
      $compra=DB::table('compras')
      ->where('compras.id',$id)
      ->selectRaw('compras.*,proveedores.*, compras.id as idre')
      ->join('proveedores','compras.id_proveedor','=','proveedores.id')
      ->first();
      return view('abonos.edit',compact('abonos','compra'));
    }

    public function update(Request $request, $id)
    {
      app('App\Http\Controllers\proveedoresController')->comprueba();
      $abonos=DB::table('abonos')
      ->where('estado',1)
      ->where('id_compra',$id)
      ->orderBy('fecha','asc')
      ->get();

      $cont=0;
      foreach($abonos as $p){
        $cont=$cont+$p->cantidad;
      }
      $compra=DB::table('compras')
      ->where('id',$id)
      ->first();
      $restan=$compra->importe-$cont;
      if($request->cantidad>$restan){
        return redirect()->route('abonos.edit',$id)->with('info','la cantidad excede el restante');
      }else{
        DB::table('abonos')
        ->insert(
            [
              'cantidad' => $request->cantidad,
              'descripcion'=> $request->descripcion,
              'fecha' => $request->fecha,
              'id_compra' => $id,
            ]
        );
        return redirect()->route('abonos.edit',$id)->with('info','Se guardó correctamente');
      }

    }
    public function store(Request $request, $id)
    {

    }
    public function destroy(Request $request, $id)
    {
      DB::table('abonos')
      ->where('id',$id)->update(
          [
            'estado' => 2
          ]
      );
    return redirect()->route('abonos.edit',$request->val)->with('info','Se eliminó correctamente');
    }

}

resources/views/abonos/create.blade.php
@extends('layouts.main')

@section('seccion')
  Proveedores / Crear
@endsection

@section('titulo')
  Nuevo Proveedor
@endsection

@section('descripcion')
  Agregar datos de proveedor
@endsection


@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection

@section('contenido')

  <form action="{{route('proveedores.create')}}"  method="POST">
    <input type="hidden" name="_method" value="PUT">
    <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
    <div class="form-group">
      <label for="exampleForm2">Nombre</label>
      <input type="text" name="nombre" id="nombre" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Negocio</label>
      <input type="text" name="negocio" id="negocio" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Dirección</label>
      <input type="text" name="direccion" id="direccion" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Colonia</label>
      <input type="text" name="colonia" id="colonia" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Población</label>
      <input type="text" name="poblacion" id="poblacion" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Teléfono</label>
      <input type="text" name="telefono" id="telefono" class="form-control">
    </div>

    <div class="form-group">
      <label for="exampleForm2">Correo</label>
      <input type="text" name="correo" id="correo" class="form-control">
    </div>

    <div class="d-flex">
      <div class="mr-auto p-2">
        <button type="submit" class="btn  btn-info text-white">Guardar</button>
        <a href="{{route('proveedores.index')}}" class="btn  btn-secondary">Cancelar</a>
      </div>
    </div>
  </form>
@endsection

resources/views/abonos/edit.blade.php
@extends('layouts.main')

@section('seccion')
  abonos / Registrar
@endsection

@section('titulo')
  Compra: {{$compra->idre}} <br>
  Proveedor: {{$compra->nombre}} <br>
  Total de la compra: ${{number_format($compra->importe,2)}}
@endsection

@section('descripcion')
  Añadir abono a la compra
@endsection



@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection

@section('contenido')
<table class="table table-hover table-outline text-center">
  <thead class="thead-light">
        <tr>
          <th scope="col">Fecha</th>
          <th scope="col">Descripcion</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Quitar</th>
        </tr>
      </thead>
      <tbody>
        @php
          $cont=0;
        @endphp
        @foreach($abonos as $p)
          <tr>
            <td>{{$p->fecha}}</td>
            <td>{{$p->descripcion}}</td>
            <th scope="row">${{number_format($p->cantidad,2)}}</th>
            <td>
              {!! Form::open(['route'=>['abonos.destroy', $p->id], 'method'=>'DELETE', 'id'=>'formDes','onsubmit'=>'return confirm("¿Seguro que desea eliminarlo?")']) !!}
                <button type="submit" class="btn-info btn text-white" name="button"><i class="fa fa-trash "></i></button>
                <input type="hidden" name="val" value="{{$compra->idre}}">
              {!!Form::close()!!}
            </td>
            @php
            $cont=$cont+$p->cantidad;
            @endphp
          </tr>
        @endforeach
        <tr>
          <td>

          </td>
          <th>
            Total pagado:
          </th>
          <th scope="row">
            ${{number_format($cont,2)}}
          </th>
          <td>

          </td>
        </tr>
        <tr>
          <td>

          </td>
          <th>
            Pendiente de abono:
          </th>
          <th scope="row">
            ${{number_format($compra->importe-$cont,2)}}
          </th>
          <td>

          </td>
        </tr>
      </tbody>
    </table>
    <br><br>
    <h4>Añadir nuevo abono</h4>
    <form action="{{route('abonos.update',$compra->idre)}}"  method="POST">
      <input type="hidden" name="_method" value="PUT">
      <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
      <div class="form-group">
        <label for="cantidad">Cantidad</label>
        <input type="number"  required step="0.01" name="cantidad" id="cantidad" class="form-control">
      </div>

      <div class="form-group">
        <label for="descripcion">Descripción</label>
        <input type="text" required name="descripcion" id="descripcion" class="form-control">
      </div>
      <div class="form-group">
        <label for="fecha">Fecha</label>
        <div class="col-2">
          <input type="date" required name="fecha" id="fecha" class="form-control">
        </div>
      </div>



      <div class="d-flex">
        <div class="mr-auto p-2">
          <button type="submit" class="btn  btn-info text-white">Guardar</button>
          <a href="{{route('compras.index')}}" class="btn  btn-secondary">Regresar</a>
        </div>
      </div>
    </form>
@endsection

resources/views/abonos/index.blade.php
@extends('layouts.main')

@section('seccion')
  Proveedores
@endsection

@section('titulo')
  Gestor de proveedores
@endsection

@section('boton')
  <a href="{{route('proveedores.create')}}" class="btn  btn-info text-white"><i class="fa fa-plus"></i> Registrar nuevo proveedor</a>
@endsection

@section('descripcion')
  Panel de control para gestionar los proveedores
@endsection


@section('opciones')
  <!--<button class="btn btn-success float-right" type="button">
    <i class="icon-cloud-download"></i>
  </button>
  <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
    <label class="btn btn-outline-secondary">
      <input id="option1" type="radio" name="options" autocomplete="off"> Day
    </label>
    <label class="btn btn-outline-secondary active">
      <input id="option2" type="radio" name="options" autocomplete="off" checked=""> Month
    </label>
    <label class="btn btn-outline-secondary">
      <input id="option3" type="radio" name="options" autocomplete="off"> Year
    </label>
  </div>-->
@endsection


@section('contenido')
{{Form::open(['route'=>'proveedores.index','method'=>'GET'])}}
  @include('layouts.busqueda')
{{Form::close()}}
  <table class="table table-hover table-outline text-center">
    <thead class="thead-light">
      <tr>
        <th scope="col">Código</th>
        <th scope="col">Proveedor</th>
        <th scope="col">Dirección</th>
        <th scope="col">Negocio</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Correo</th>
        <th scope="col">Editar</th>
      </tr>
    </thead>
    <tbody>
      @foreach($proveedores as $c)
        <tr>
          <th scope="row">{{$c->id}}</th>
          <td>{{$c->nombre}}</td>
          <td>{{$c->direccion}}</td>
          <td>{{$c->negocio}}</td>
          <td>{{$c->telefono}}</td>
          <td>{{$c->correo}}</td>
          <td>
            <a class="btn  btn-info text-white" href="{{route('proveedores.edit',$c->id)}}"><i class="icon-pencil "></i></a>
          </td>
        </tr>
      @endforeach

    </tbody>
  </table>
  {!!$proveedores->appends(Request::only(['nombre']))->render()!!}
  <script type="text/javascript">
    function cerrar() {
        $('#not').remove();
    }
  </script>

@endsection