routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('clientes.index');
});

Route::get('/home', function(){
	return redirect()->route('clientes.index');
})->name('home');

Route::post('/contacto','ContactoController@contacto')->name('contacto');

Route::resource('/tickets','TicketsController')->middleware('auth');

Route::resource('/remisiones','RemisionesController')->middleware('auth');
Route::resource('/compras','ComprasController')->middleware('auth');

Route::resource('/clientes','ClientesController')->middleware('auth');
Route::resource('/proveedores','ProveedoresController')->middleware('auth');

Route::resource('/laboratorios','LaboratoriosController')->middleware('auth');
Route::resource('/medicamentos','MedicamentosController')->middleware('auth');
Route::resource('/rutas','RutasController')->middleware('auth');

Route::post('/reporteClientes','ReportesController@reporteClientes')->name('reporteClientes')->middleware('auth');
Route::post('/reporteProveedores','ReportesController@reporteProveedores')->name('reporteProveedores')->middleware('auth');


Route::get('/ticketsAs','TicketsController@ticketsAs')->name('ticketsAs');
Route::get('/provsAs','TicketsController@provsAs')->name('provsAs');
Route::get('/rutasAs','RutasController@rutasAs')->name('rutasAs');
Route::get('/ticketAs','TicketsController@ticketAs')->name('ticketAs');
Route::get('/ticketPAs','TicketsController@ticketPAs')->name('ticketPAs');
Route::get('/laboratorioAs','LaboratoriosController@laboratorioAs')->name('laboratorioAs');
Route::get('/descripcionAs','RemisionesController@descripcionAs')->name('descripcionAs');

Route::get('/cambiar', 'UsuariosController@cambiar')->name('cambiar')->middleware('auth');
Route::post('/cambio', 'UsuariosController@cambio')->name('cambio')->middleware('auth');
Route::resource('/usuarios','UsuariosController')->middleware('auth');

Route::resource('/pagos','PagosController')->middleware('auth');
Route::resource('/abonos','AbonosController')->middleware('auth');

Route::get('/catalogos', 'MedicamentosController@catalogos')->name('catalogos')->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('', 'GESTRA') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('', 'GESTRA') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                           
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/busqueda.blade.php
  <div class="input-group mb-4" style="margin-bottom:10px">
    <div class="input-group-prepend">
      <div class="input-group-text">
        <i class="cui-magnifying-glass"></i>
      </div>
    </div>
    <input type="text" class="form-control" id="busquedaId" name="busquedaId" placeholder="Buscar" >
  </div>

resources/views/layouts/footer.blade.php
  <footer class="app-footer oculto-impresion">
    <div>
      <a class="text-info">DAGISA</a>
      <span>&copy; 2021.</span>
    </div>
    <div class="ml-auto">
      <span>Desarrollado por</span>
      <a class="text-info"target="_blank" href="https://api.whatsapp.com/send?phone=+529511489184">NOVA Social Media.</a>
    </div>
  </footer>
  <!-- CoreUI and necessary plugins-->

</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.15
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>DAGISA: SISTEMA OPERATIVO</title>
    <!-- Icons-->
    <link rel="icon" type="image/ico" href="{{asset('pan/img/brand/sygnet.ico')}}" sizes="any" />
    <link href="{{asset('pan/node_modules/@coreui/icons/css/coreui-icons.min.css')}}" rel="stylesheet">
    <link href="{{asset('pan/node_modules/flag-icon-css/css/flag-icon.min.css')}}" rel="stylesheet">
    <link href="{{asset('pan/node_modules/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('pan/node_modules/simple-line-icons/css/simple-line-icons.css')}}" rel="stylesheet">
    <!-- Main styles for this application-->
    <link href="{{asset('pan/css/style.css')}}" rel="stylesheet">
    <link href="{{asset('pan/vendors/pace-progress/css/pace.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href=" {{asset('pan/css/jquery-ui.theme.min.css')}} ">
    <link rel="stylesheet" type="text/css" href=" {{asset('pan/css/jquery-ui.min.css')}} ">
    <link rel="stylesheet" href="{{ asset('pan/css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('libs/bootstrap-datepicker/css/bootstrap-datepicker.css') }}" >

    <!-- Global site tag (gtag.js) - Google Analytics-->

    <script src="{{asset('pan/node_modules/jquery/dist/jquery-1.12.4.js')}}"></script>

    <script src="{{asset('/js/gijgo.min.js')}}" type="text/javascript"></script>
    <link href=" {{asset('css/gijgo.min.css')}}" rel="stylesheet" type="text/css" />

    <script src="{{ asset('libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}" charset="utf-8"></script>


<!--    <script src="{{asset('pan/node_modules/jquery/dist/jquery.min.js')}}"></script>-->

    <script src="{{asset('pan/node_modules/popper.js/dist/umd/popper.min.js')}}"></script>
    <script src="{{asset('pan/node_modules/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('pan/node_modules/pace-progress/pace.min.js')}}"></script>
    <script src="{{asset('pan/node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('pan/node_modules/@coreui/coreui/dist/js/coreui.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('pan/js/jquery-ui.min.js')}}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      // Shared ID
      gtag('config', 'UA-118965717-3');
      // Bootstrap ID
      gtag('config', 'UA-118965717-5');
    </script>
    </head>

resources/views/layouts/main.blade.php
@include('layouts.header')

    @include('layouts.menu')

@include('layouts.footer')

resources/views/layouts/menu.blade.php
  <body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    <header class="app-header navbar">
      <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img class="navbar-brand-full" src="{{asset('pan/img/brand/logo.png')}}" width="120" alt="SICA">
        <img class="navbar-brand-minimized" src="{{asset('pan/img/brand/sygnet.png')}}" width="30" height="30" alt="SICA">
      </a>
      <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
          <a class="nav-link" href="/">Inicio</a>
        </li>

        <li class="nav-item px-3">
          <a class="nav-link" href="{{route('usuarios.index')}}">Usuarios</a>
        </li>


      </ul>
      <ul class="nav navbar-nav ml-auto" style="margin-right:1.5%">
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            {{Auth::user()->name}}<img class="img-avatar" src="{{asset('pan/img/avatars/6.png')}}" alt="admin@bootstrapmaster.com">
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-header text-center">
              <strong>Ajustes</strong>
            </div>
            <a class="dropdown-item" href="{{route('usuarios.index')}}">
              <i class="fa fa-users"></i> Usuarios
            </a>
            <a class="dropdown-item" href="{{route('cambiar')}}">
              <i class="fa fa-wrench"></i> Cambiar Contraseña</a>
            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
              <i class="fa fa-lock"></i>
                Cerrar Sesión
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
            </a>


          </div>
        </li>
      </ul>

    </header>
    <div class="app-body">
      @include('layouts.menulateral')
      <main class="main">
        <!-- Breadcrumb-->
        <ol class="breadcrumb oculto-impresion">
          <li class="breadcrumb-item text-success">
            @yield('seccion')
          </li>
        </ol>
        <div class="container-fluid">
          <div class="animated fadeIn">

            <!-- /.row-->
            <div class="card">
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-6">
                    <h4 class="card-title mb-0">@yield('titulo')</h4>
                    <div class="small text-muted">@yield('descripcion')</div>
                  </div>
                  <div class="col-sm-6 text-right" >
                    <h4 class="card-title mb-0">@yield('boton')</h4>
                  </div>

                  <!-- /.col-->
                  <div class="col-sm-7 d-none d-md-block">
                    @yield('opciones')
                  </div>
                  <!-- /.col-->
                </div>
                @if (Session::has('info'))
                  <div style="margin-top:15px;" class="alert alert-primary alert-dismissible fade show" role="alert">
                    {{Session::get('info')}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                @endif

                @if ($errors->any())
                  <div style="margin-top:15px;" class="alert alert-danger alert-dismissible fade show" role="alert">
                    @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                    @endforeach
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                @endif
                <!-- /.row-->
                <div  style="margin-top:15px;">

                  @yield('contenido')

                </div>
              </div>
              <!--<div class="card-footer">
                <div class="row text-center">
                </div>
              </div>-->
            </div>
          </div>
        </div>
      </main>
    </div>
  </body>

resources/views/layouts/menulateral.blade.php
<div class="sidebar">
  <nav class="sidebar-nav c-sidebar-dark c-sidebar-show">
    <ul class="nav">
      <li class="nav-title">Menu principal</li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('usuarios.index')}}">
            <i class="nav-icon fa fa-users"></i> Usuarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('clientes.index')}}">
            <i class="nav-icon fa fa-address-book-o"></i> Clientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('remisiones.index')}}">
            <i class="nav-icon fa fa-file-pdf-o"></i> Remisiones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('tickets.index')}}">
            <i class="nav-icon fa fa-ticket"></i> Tickets</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('proveedores.index')}}">
            <i class="nav-icon fa fa-handshake-o"></i> Proveedores</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{route('compras.index')}}">
            <i class="nav-icon fa fa-shopping-cart"></i> Compras</a>
        </li>
        <li class="nav-item nav-dropdown">
          <a class="nav-link nav-dropdown-toggle font-weight-bold" href="#">
            <i class="nav-icon fa fa-book"></i>Catalogos
            </a>
          <ul class="nav-dropdown-items">
            <li class="nav-item">
              <a class="nav-link" href="{{route('laboratorios.index')}}"><i class="nav-icon fa fa-flask"></i>Laboratorios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{route('medicamentos.index')}}"><i class="nav-icon fa fa-medkit"></i>Medicamentos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{route('catalogos')}}"><i class="nav-icon fa fa-print"></i>Imprimir catálogo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{route('rutas.index')}}"><i class="nav-icon fa fa-car"></i>Rutas</a>
            </li>
          </ul>
      </li>
        <li class="nav-item nav-dropdown">
          <a class="nav-link nav-dropdown-toggle font-weight-bold" href="#">
            <i class="nav-icon icon-list"></i>Reportes
            </a>
          <ul class="nav-dropdown-items">
            <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#exampleModalCenter"><i class="nav-icon fa fa-file-pdf-o"></i>Saldo final clientes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#exampleModalProveedores"><i class="nav-icon fa fa-file-pdf-o"></i>Saldo final proveedores</a>
            </li>
          </ul>
      </li>
    </ul>
  </nav>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      {!!Form::open(['route'=> 'reporteClientes','files'=>'false','id'=>'formCreate','target'=>'_blank'])!!}
      <div class="modal-header">
        <h5 class="modal-title" id="modalInsercionCenterTitle">Reporte de saldos clientes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
            <div class="input-group mb-2 mr-sm-2">
              <div class="alert alert-info" role="alert">
                Si deja el campo de NOMBRE vacío, el reporte hará un acumulado de todos sus clientes
              </div>
              <input type="text" id="nombreM" name="nombre" style="text-transform: uppercase" class="form-control" placeholder="NOMBRE">
              <input type="text" id="idM" hidden name="id"  class="form-control mb-2" >
              <div class="input-group-prepend">
               <a class="input-group-text btn  btn-danger" onclick="limpiarCampoM()">
                <i class="fa fa-trash-o"></i>
               </a>
              </div>
            </div>
            <br>
            <div class="input-group date">
              <input type="date" name="fecha" data-toggle="tooltip" data-placement="top" title="Fecha inicial" required="required" placeholder="Fecha inicial" autocomplete="off" id="datepicker1" class="datepicker form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
              <input type="date" name="fechafin" data-toggle="tooltip" data-placement="top" title="Fecha final" required="required" placeholder="Fecha final" autocomplete="off" id="datepicker2" class="datepicker form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
            </div>
            <br>
            <select required name="estado" class="custom-select">
              <option value="1">Pagadas</option>
              <option value="2">Pagadas a destiempo</option>
              <option value="3">En tiempo</option>
              <option value="4">No pagadas</option>
              <option value="5">Todas</option>
            </select>

      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-info text-white" >Generar</button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalProveedores" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      {!!Form::open(['route'=> 'reporteProveedores','files'=>'false','id'=>'formCreate','target'=>'_blank'])!!}
      <div class="modal-header">
        <h5 class="modal-title" id="modalProveedoresCenterTitle">Reporte de saldos proveedores</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
            <div class="input-group mb-2 mr-sm-2">
              <div class="alert alert-info" role="alert">
                Si deja el campo de NOMBRE vacío, el reporte hará un acumulado de todos sus proveedores
              </div>
              <input type="text" id="nombreP" name="nombre" style="text-transform: uppercase" class="form-control" placeholder="NOMBRE">
              <input type="text" id="idP" hidden name="id"  class="form-control mb-2" >
              <div class="input-group-prepend">
               <a class="input-group-text btn  btn-danger" onclick="limpiarCampoM()">
                <i class="fa fa-trash-o"></i>
               </a>
              </div>
            </div>
            <br>
            <div class="input-group date">
              <input type="date" name="fecha" data-toggle="tooltip" data-placement="top" title="Fecha inicial" required="required" placeholder="Fecha inicial" autocomplete="off" id="datepicker1" class="datepicker form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
              <input type="date" name="fechafin" data-toggle="tooltip" data-placement="top" title="Fecha final" required="required" placeholder="Fecha final" autocomplete="off" id="datepicker2" class="datepicker form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
            </div>
            <br>
            <select required name="estado" class="custom-select">
              <option value="1">Pagadas</option>
              <option value="2">Pagadas a destiempo</option>
              <option value="3">En tiempo</option>
              <option value="4">No pagadas</option>
              <option value="5">Todas</option>
            </select>

      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-info text-white" >Generar</button>
        </div>
      </form>
    </div>
  </div>
</div>
<style media="screen">
  .ui-autocomplete {
    z-index: 5000;
  }
</style>
<script type="text/javascript">
  function limpiarCampoM() {
    $("#nombreM").val("");
    $("#idM").val("");
    $("#nombreM").attr('disabled', false);
    $("#nombreP").val("");
    $("#idP").val("");
    $("#nombreP").attr('disabled', false);
  }
  const clienteM = {
       source: '/ticketAs',
       minLength: 2,
       autoFocus: true,
       select:function (e,ui) {

          $("#idM").val(ui.item.id);
          $("#nombreM").attr('disabled', true);
       }
  };

  $('#nombreM').autocomplete(clienteM);
  $( "#nombreM" ).autocomplete( "option", "appendTo", ".eventInsForm" );
  const proveedorM = {
       source: '/ticketPAs',
       minLength: 2,
       autoFocus: true,
       select:function (e,ui) {

          $("#idP").val(ui.item.id);
          $("#nombreP").attr('disabled', true);
       }
  };

  $('#nombreP').autocomplete(proveedorM);
  $( "#nombreP" ).autocomplete( "option", "appendTo", ".eventInsForm" );
</script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>